baseURL = "https://sergisanchezz.github.io/"
title = "Sergi Sanchez Orvay"
languageCode = "en-us"
theme = "hello-friend-ng"
publishDir = "docs"

[params]
  homeSubtitle = "Robotics Research Intern at BMW Group (RoboTac Lab) • MSc Robotics, Systems and Control Student at ETH Zürich"

# Social icons
[[params.social]]
  name = "github"
  url  = "https://github.com/sergisanchezz"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/sergisanchezz/"

[[params.social]]
  name = "email"
  url  = "mailto:sergi.sanchez.orvay@gmail.com"

[[params.social]]
  name = "googlescholar"
  url  = "https://scholar.google.com/citations?user=C5gvgE8AAAAJ&hl=en"

[params.logo]
  logoText = "Sergi Sanchez Orvay"
  logoHomeLink = "/"

[menu]
[[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about/"
    weight     = 1

[[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 2

[[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications/"
    weight     = 3
  
[[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news/"
    weight     = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true